### ISSUE TITLE
Nuix v9 support?

### ISSUE THREAD

**Issue by marleyjaffe** [Nuix/Custom-Exporter#11]
We are using Nuix `v9.10.18` and experiencing issues with this script (additional issue ticket to follow). Is this script certified or tested for any nuix version newer than `8.8` like the readme has listed?

**Comment by JuicyDragon** [comment]
Hello @marleyjaffe the tested in badge is something I include to note what version I had last tested a script to be working in.  The scripts on GitHub don't really get preemptive updates these days.  I often will try to fix issues when reported assuming, the issue is not a huge undertaking.

After you provide details regarding the issue you are seeing we will see what we can do.  My hope is that it is a simple issue to resolve as the API usually doesn't change too drastically between versions.

**Comment by marleyjaffe** [comment]
#12 issue created for our specific issue.
