### ISSUE TITLE
Name files for Production Document ID

### ISSUE THREAD

**Issue by drobins7MAC** [Nuix/Custom-Exporter#5]
Hi.  Love this script.  Tried to customize the output so that the document ids would be the exported natives and txt file names.  Instead I ended up with a bunch of files named {documentsids}.xls, {documentsids}.msg, {documentsids}.txt and so on.  What do I enter into the dialog so that files are named for the doc ids of the production I'm exports?  (FYI - didn't use the export production because I'm running searches to export in batches of 100k rather than the whole 2 million items in the production at once.)

**Comment by JuicyDragon** [comment]
Hello @drobins7MAC always nice to hear that someone is finding these scripts of use!

I believe you are looking for the placeholder `{docid}`:

`{docid}`: Replaced with a previously assigned DOCID based on a production set selected in the **Placeholders Tab** when **Enable {docid} placeholder** is checked. Will be replaced with item's GUID if no document ID is able to be found for the given item or no production set is selected on the Placeholders Tab.

Does that make sense?  If not I can elaborate further.  Also since that script is a bit on the complex side, it has an included Help.html file.  The **Help** menu entry in the script's settings dialog will display it.  Within that there is a **Placeholders** sections in which I talk a bit about the various placeholders and their behavior.
