### ISSUE TITLE
Running export looks for a TEMP folder which doesn't exist

### ISSUE THREAD

**Issue by seanpowell75** [Nuix/Custom-Exporter#9]
Hi there, I had this issue once before with different settings but I was unable to replicate it at the time.  Its just cropped up again.
Running an export of Natives only, and using the {custom_1} placeholder to name the files.  This field holds my DocID over several different production sets - in this particular case, its in the format ABC.123.1234567 rather than ringtail formatted.

Minor issue - my loadfile doesn't match my output - the export script requires ringtail format, I can't reference the {custom_1} field for naming the DocID's inside the loadfile (only {docid} for a single production set), so the loadfile starts at 001.001.001 even though my outputted natives are named correctly and the item path referencing them is correct.  I plan to fix this with some excel vlookups after the event though.

Major issue - the script terminates with the error attached.  When I check, there is no TEMP folder, and the file loadfile.dat exists directly in the root of my export folder "2. Missings natives 2".  What's particularly wierd is that I ran this exact process previously and it worked fine, all i changed here was selecting a different set of docs in the nuix gui and incrementing the folder name to "2".

[custom exporter error.txt](https://github.com/Nuix/Custom-Exporter/files/6073175/custom.exporter.error.txt)

**Comment by JuicyDragon** [comment]
Hello @seanpowell75 sorry it took me a little while to get back to you, been busy working on some other things.

Did you specify the items to export by specifying a query or perhaps using items which were excluded?  It looks like the export had no items to work with:

```
Getting input items...
Removing any excluded items...
Removing any evidence container items...
Input Items: 0
```

I was a little surprised that I didn't have a check in there already for when this happens.

Regarding the minor issue I don't think that is something I'll be able to address any time soon unfortunately.  This script doesn't actually perform a customized export, but instead modifies an export after Nuix has performed it.  I don't have anything in place to rebuild Ringtail load file unfortunately.

I've made an update to the script so that it will now halt if it ends up without items to actually export.  I've also added some additional log messages as it optionally includes families, removes excluded items and removes evidence container items to hopefully help clarify how those steps changed the item count:

![image](https://user-images.githubusercontent.com/11775738/110018898-a94d5900-7cdc-11eb-8a6c-c937339d3e40.png)

https://github.com/Nuix/Custom-Exporter/releases/tag/v1.21.0

**Comment by seanpowell75** [comment]
Thanks Jason.  I’ve re-tested with the v21 script – I think the error is due to the fact that (unusually I guess) this is attempting to export items that are part of various exclusions sets.  So I select my items in nuix, and the script confirms the items are selected for inclusion, but then when the script runs it also removes excluded items, so that’s how I end up with 0 items which triggers the error.  Thanks for looking into it.

Sean Powell | Associate Director, Forensic
+61 8 9263 7273
spowell5@kpmg.com.au<mailto:spowell5@kpmg.com.au>

[KPMG]<http://www.kpmg.com.au/>

**Comment by seanpowell75** [comment]
Also discovered during some further testing that attempting to export items with an audited size of 0 also causes the script to terminate with an error – these are usually moved to an exclusion set during QA so encountering them should be a rarity, but thought I would pass that on for future script dev

rgds

Sean Powell | Associate Director, Forensic
+61 8 9263 7273
spowell5@kpmg.com.au<mailto:spowell5@kpmg.com.au>

[KPMG]<http://www.kpmg.com.au/>

**Comment by JuicyDragon** [comment]
Might you be able to share the error message you are seeing or a little more detail about when you're seeing this?  I just ran a test with some items that have an audited size of 0 on my end and they seem to export fine so I'm thinking it may be a combination of things that maybe causing the issue.  Thanks

**Comment by seanpowell75** [comment]
Ok, oddly enough, I’ve been unable to replicate it.  Perhaps there was something glitchy with the items I had selected before.  The error said something like “cannot process empty blocks”

The basic process I was following was to select items with audited size:0 and then run the script for Native output only using the template {export_directory}\NATIVE\{custom_1}.{extension} and with {custom_1} set on the Placeholders tab to the cm field “FH_RelativityDocID.

But as I say it worked this time so perhaps the items I had selected had other issues.  Sorry – I didn’t take note of the items that I was attempting the first time I hit that.

Thanks


Sean Powell | Associate Director, Forensic
+61 8 9263 7273
spowell5@kpmg.com.au<mailto:spowell5@kpmg.com.au>

[KPMG]<http://www.kpmg.com.au/>

**Comment by JuicyDragon** [comment]
That error doesn't sound familiar I don't think.  If you run into it again and have any more context I'd be interested to hear about it so I can look into it further 😄 
Thanks
